pipeline {
    agent any
  tools {
    maven 'maven-3.9.9'
}
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
        stage('complete') {
            steps {
                echo 'test completed'
            }
        }
        stage('check') {
            steps {
                echo 'check completed'

            }
        }
    }

}
